# Generated by Django 4.2.27 on 2026-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Adı')),
                ('achievement_type', models.CharField(choices=[('gold_medal', 'Qızıl Medal'), ('silver_medal', 'Gümüş Medal'), ('bronze_medal', 'Bürünc Medal'), ('certificate', 'Sertifikat'), ('diploma', 'Diploma'), ('award', 'Mükafat'), ('title', 'Fəxri Ad')], max_length=50, verbose_name='Növü')),
                ('issuer', models.CharField(blank=True, help_text='Məs: Azərbaycan Kulinariya Federasiyası', max_length=200, verbose_name='Verən qurum')),
                ('description', models.TextField(blank=True, verbose_name='Ətraflı məlumat')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='İl')),
                ('competition_name', models.CharField(blank=True, max_length=200, verbose_name='Müsabiqə/Yarışma adı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Şəkil/Skan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nailiyyət',
                'verbose_name_plural': 'Nailiyyətlər',
                'ordering': ['order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Məhsulun adı')),
                ('tagline', models.CharField(blank=True, max_length=250, verbose_name='Slogan/Qısa cümlə')),
                ('description', models.TextField(verbose_name='Haqqında')),
                ('launch_year', models.IntegerField(blank=True, null=True, verbose_name='Buraxılış ili')),
                ('website_url', models.URLField(blank=True, verbose_name='Sayt')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/products/', verbose_name='Şəkil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, help_text='Ana səhifədə göstər', verbose_name='Öne çıxan')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ['order', '-launch_year'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Restoranın adı')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Haqqında')),
                ('short_description', models.CharField(help_text='Kartda göstəriləcək qısa məlumat', max_length=250, verbose_name='Qısa məlumat')),
                ('cuisine_type', models.CharField(blank=True, help_text='Məs: Azərbaycan, Avropa, Fast Food', max_length=100, verbose_name='Mətbəx növü')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ünvan/Şəhər')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Rezervasiya nömrəsi')),
                ('website_url', models.URLField(blank=True, help_text='Rəsmi sayt varsa daxil edin', verbose_name='Rəsmi sayt')),
                ('instagram_url', models.URLField(blank=True, help_text='Rəsmi sayt yoxdursa Instagram linki', verbose_name='Instagram')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', verbose_name='Üz şəkli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, help_text='Kiçik rəqəm əvvəl göstərilir', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restoran',
                'verbose_name_plural': 'Restoranlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Verlişin adı')),
                ('channel', models.CharField(blank=True, max_length=100, verbose_name='Kanal/Platforma')),
                ('country', models.CharField(blank=True, help_text='Məs: Azərbaycan, Rusiya', max_length=100, verbose_name='Ölkə')),
                ('show_type', models.CharField(choices=[('competition', 'Müsabiqə'), ('educational', 'Təhsil/Tədris'), ('entertainment', 'Əyləncə'), ('documentary', 'Sənədli')], default='competition', max_length=50, verbose_name='Növ')),
                ('description', models.TextField(verbose_name='Haqqında')),
                ('year', models.IntegerField(blank=True, help_text='İştirak ili', null=True, verbose_name='İl')),
                ('result', models.CharField(blank=True, help_text='Məs: Qalib, 2-ci yer, İştirakçı', max_length=200, verbose_name='Nəticə/Yer')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='projects/shows/', verbose_name='Poster/Şəkil')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube linki')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, help_text='Ana səhifədə göstər', verbose_name='Öne çıxan')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veriliş',
                'verbose_name_plural': 'Verilişlər',
                'ordering': ['order', '-year'],
            },
        ),
    ]
