# Generated by Django 5.2 on 2026-01-26 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Primary phone number for contact', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Optional physical address')),
                ('is_active', models.BooleanField(default=True, help_text='Use this contact information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters long')])),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant Management'), ('music', 'Music Training')], max_length=50)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long')])),
                ('years_experience', models.IntegerField(help_text='Number of years of experience in this area')),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage highlights')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-years_experience', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters long')])),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant Management'), ('music', 'Music Training')], max_length=50)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long')])),
                ('icon', models.CharField(help_text='CSS class for icon display', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
